In [24]:
import pandas as pd

In [25]:
# read data
df = pd.read_csv("sampled_crime_data.csv")

In [26]:
df.dtypes

Case Number              object
Date                     object
Block                    object
IUCR                     object
Primary Type             object
Description              object
Location Description     object
Arrest                     bool
Domestic                   bool
Beat                      int64
Ward                    float64
FBI Code                 object
X Coordinate            float64
Y Coordinate            float64
Year                      int64
Latitude                float64
Longitude               float64
Location                 object
ID                      float64
District                float64
Community Area          float64
Updated On               object
dtype: object

In [42]:
# required datetime conversion
df['Date'] = df['Date'].astype('datetime64[ns]')
df['Updated On'] = df['Updated On'].astype('datetime64[ns]')

# integer type conversion
df['ID'] = df['ID'].astype('Int64')
df['Ward'] = df['Ward'].astype('Int64')
df['District'] = df['District'].astype('Int64')
df['Community Area'] = df['Community Area'].astype('Int64')

# categorical conversion
df["Primary Type"] = df["Primary Type"].astype("category", )
df["Description"] = df["Description"].astype("category")
df["Location Description"] = df["Location Description"].astype("category")
df["FBI Code"] = df["FBI Code"].astype("category")
df["Block"] = df["Block"].astype("category")
df["IUCR"] = df["IUCR"].astype("category")

In [ ]:
df.dtypes

In [44]:
df.isna().sum()

Case Number                0
Date                       0
Block                      0
IUCR                       0
Primary Type               0
Description                0
Location Description    2204
Arrest                     0
Domestic                   0
Beat                       0
Ward                       1
FBI Code                   0
X Coordinate            2098
Y Coordinate            2098
Year                       0
Latitude                2098
Longitude               2098
Location                2098
ID                         0
District                   0
Community Area            14
Updated On                 0
dtype: int64

In [ ]:
# since null values are less than 5% we are dropping rows with null values

df = df.dropna(subset=["X Coordinate"])
df = df.dropna(subset=["Community Area"])
df = df.dropna(subset=["Location Description"])

In [50]:
df.isna().sum()

Case Number             0
Date                    0
Block                   0
IUCR                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
Ward                    0
FBI Code                0
X Coordinate            0
Y Coordinate            0
Year                    0
Latitude                0
Longitude               0
Location                0
ID                      0
District                0
Community Area          0
Updated On              0
dtype: int64

In [48]:
df. shape

(497902, 22)

In [51]:
df.head()

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,Ward,FBI Code,X Coordinate,Y Coordinate,Year,Latitude,Longitude,Location,ID,District,Community Area,Updated On
0,JK184891,2026-03-18,069XX S CORNELL AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,332,5,08B,1188552.0,1859230.0,2026,41.768797,-87.584413,POINT (-87.584412909 41.768797328),14139805,3,43,2026-03-25 15:57:05
1,JK184982,2026-03-18,082XX S CORNELL AVE,0820,THEFT,$500 AND UNDER,VEHICLE NON-COMMERCIAL,False,False,411,8,06,1188698.0,1850652.0,2026,41.745255,-87.584152,POINT (-87.584151569 41.745255037),14139911,4,45,2026-03-25 15:57:05
2,JK188256,2026-03-18,034XX N RIDGEWAY AVE,0810,THEFT,OVER $500,RESIDENCE,False,False,1732,30,06,1150784.0,1922573.0,2026,41.943437,-87.721197,POINT (-87.721197255 41.943437198),14142669,17,21,2026-03-25 15:57:05
4,JK186910,2026-03-18,072XX S DAMEN AVE,1130,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,RESIDENCE,False,False,735,17,11,1164278.0,1856611.0,2026,41.762156,-87.673463,POINT (-87.673462943 41.762155987),14141280,7,67,2026-03-25 15:57:05
5,JK185040,2026-03-18,032XX N RICHMOND ST,0760,BURGLARY,BURGLARY FROM MOTOR VEHICLE,STREET,False,False,1733,33,06,1156145.0,1921418.0,2026,41.940161,-87.701524,POINT (-87.701524029 41.940161052),14139899,17,21,2026-03-25 15:57:05

In [52]:
df.tail()

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,Ward,FBI Code,X Coordinate,Y Coordinate,Year,Latitude,Longitude,Location,ID,District,Community Area,Updated On
499995,JH168561,2024-02-28 06:05:00,038XX N ASHLAND AVE,0610,BURGLARY,FORCIBLE ENTRY,BAR OR TAVERN,False,False,1922,47,05,1164974.0,1925345.0,2024,41.950754,-87.668963,POINT (-87.668962751 41.950753786),13382369,19,6,2024-12-21 15:40:46
499996,JH171253,2024-02-28 06:00:00,056XX W BYRON ST,0810,THEFT,OVER $500,RESIDENCE,False,False,1633,38,06,1138141.0,1925361.0,2024,41.951326,-87.767600,POINT (-87.76759975 41.951326099),13385723,16,15,2024-12-21 15:40:46
499997,JH169057,2024-02-28 06:00:00,060XX S OAK PARK AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,812,13,06,1132121.0,1863662.0,2024,41.782122,-87.791162,POINT (-87.791161899 41.782121775),13382822,8,64,2024-12-21 15:40:46
499998,JH169158,2024-02-28 06:00:00,017XX S INDIANA AVE,0890,THEFT,FROM BUILDING,APARTMENT,False,False,132,3,06,1177933.0,1891878.0,2024,41.858633,-87.622346,POINT (-87.622346444 41.858633393),13383190,1,33,2024-12-21 15:40:46
499999,JH169156,2024-02-28 06:00:00,017XX S INDIANA AVE,0890,THEFT,FROM BUILDING,APARTMENT,False,False,132,3,06,1177933.0,1891878.0,2024,41.858633,-87.622346,POINT (-87.622346444 41.858633393),13383165,1,33,2024-12-21 15:40:46

In [32]:
df['Arrest'].unique()

array([False,  True])

In [35]:
df['IUCR'].unique()[:30]

array(['0486', '0820', '0810', '0460', '1130', '0760', '1153', '1320',
       '0496', '0560', '1330', '1310', '1477', '5111', '0910', '3731',
       '0710', '0430', '2825', '143A', '0860', '051A', '0930', '2870',
       '141A', '0326', '5002', '502R', '5112', '2022'], dtype=object)

In [37]:
df['Community Area'].unique()[:40]

array([43., 45., 21., 25., 67., 13., 32., 49., 22., 66.,  8., 29., 31.,
        3., 64., 28., 48., 63., 24., 19.,  6.,  2., 42.,  5., 27., 33.,
       51., 76., 15., 37., 16., 44., 35., 30., 61., 77., 23., 73., 34.,
       60.])

In [33]:
df['FBI Code'].unique()

array(['08B', '06', '11', '14', '04B', '08A', '26', '15', '07', '24',
       '04A', '03', '18', '01A', '20', '17', '02', '05', '09', '10', '16',
       '13', '22', '12', '19', '01B'], dtype=object)

In [38]:
df['ID'].unique()

array([14139805., 14139911., 14142669., ..., 13382822., 13383190.,
       13383165.], shape=(500000,))

In [34]:
df[df['Case Number'].duplicated(keep=False)]

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,Ward,FBI Code,X Coordinate,Y Coordinate,Year,Latitude,Longitude,Location,ID,District,Community Area,Updated On
4987,JK174465,2026-03-09 03:41:00,050XX S JUSTINE ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,933,20.0,01A,1166856.0,1871345.0,2026,41.802533,-87.663594,POINT (-87.663593604 41.802533268),29066.0,9.0,61.0,03/17/2026 03:42:11 PM
5024,JK174465,2026-03-09 01:03:00,050XX S JUSTINE ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,933,20.0,01A,1166856.0,1871345.0,2026,41.802533,-87.663594,POINT (-87.663593604 41.802533268),29067.0,9.0,61.0,03/17/2026 03:42:11 PM
5666,JK173315,2026-03-07 23:20:00,104XX S PEORIA ST,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,True,True,2232,21.0,01A,1172162.0,1835563.0,2026,41.704228,-87.645184,POINT (-87.645183869 41.70422778),29062.0,22.0,73.0,03/15/2026 03:48:06 PM
5667,JK173315,2026-03-07 23:20:00,104XX S PEORIA ST,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,True,True,2232,21.0,01A,1172162.0,1835563.0,2026,41.704228,-87.645184,POINT (-87.645183869 41.70422778),29063.0,22.0,73.0,03/15/2026 03:48:06 PM
24257,JK137074,2026-02-03 14:03:00,023XX W ROOSEVELT RD,0110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,False,False,1225,28.0,01A,1160870.0,1894657.0,2026,41.866630,-87.684902,POINT (-87.684901553 41.866629895),29033.0,12.0,28.0,02/11/2026 03:51:43 PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477479,JH208794,2024-04-01 11:41:00,007XX E 104TH ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,512,9.0,01A,1182889.0,1836154.0,2024,41.705608,-87.605885,POINT (-87.605885383 41.705607627),28053.0,5.0,50.0,04/09/2024 03:42:08 PM
490496,JH185734,2024-03-13 00:40:00,002XX W 109TH PL,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,513,9.0,01A,1176725.0,1832329.0,2024,41.695252,-87.628572,POINT (-87.62857189 41.695251946),28024.0,5.0,49.0,03/21/2024 03:47:52 PM
490497,JH185734,2024-03-13 00:40:00,002XX W 109TH PL,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,513,9.0,01A,1176725.0,1832329.0,2024,41.695252,-87.628572,POINT (-87.62857189 41.695251946),28023.0,5.0,49.0,03/21/2024 03:47:52 PM
490829,JH185103,2024-03-12 15:45:00,069XX S STATE ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,322,6.0,01A,1177495.0,1859111.0,2024,41.768728,-87.624946,POINT (-87.624945647 41.768727829),28019.0,3.0,69.0,03/20/2024 03:41:02 PM
490832,JH185103,2024-03-12 15:45:00,069XX S STATE ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,322,6.0,01A,1177495.0,1859111.0,2024,41.768728,-87.624946,POINT (-87.624945647 41.768727829),28018.0,3.0,69.0,03/20/2024 03:41:02 PM

In [53]:
# drop duplicate rows with the same case number as we are interested in crime ocurence
df = df.drop_duplicates(subset=["Case Number"], keep="first")

In [ ]:
# this will check for any other duplicates

df[df['Case Number'].duplicated(keep=False)]

Empty DataFrame
Columns: [Case Number, Date, Block, IUCR, Primary Type, Description, Location Description, Arrest, Domestic, Beat, Ward, FBI Code, X Coordinate, Y Coordinate, Year, Latitude, Longitude, Location, ID, District, Community Area, Updated On]
Index: []

In [55]:
# save the cleaned file as .pkl to conserve column datatypes

df.to_pickle("cleaned_chicago_crime_data.pkl")